= SBC, Reset Admin password
Oscar Andrés Carriles <ocarriles@eolos.la>
:doctype: book
:encoding: utf-8
:lang: en
:toc: left
:toclevels: 2
:numbered: yes

This tutorial will show you how you can easily reset the Restcomm-SBC Administrator's password. When you are starting with a new Restcomm-SBC installation, you will have to change the default password. For those who want to update their current password, the steps below will guide you through the process.

== Requirements

* Basic knowledge of Restcomm-SBC on Local Server.
* Basic knowledge of Restcomm-SBC directory structure.


[[reset-forgotten-administrators-password]]
== Reset Forgotten Administrators Password

In order to perform the next step, you will need to edit the *sbc.script* configuration file

* Go to the directory *$SBC_HOME/webapps/restcomm-sbc/WEB-INF/data/hsql*
* Open the file *sbc.script* for editing
* Replace the line below

[source,lang:default,decode:true]
----
INSERT INTO "restcomm_accounts" VALUES('ACae6e420f425248d6a26948c17a9e2acf','2012-04-24 00:00:00.000000','2015-01-19 07:34:08.157000','administrator@company.com','Default Administrator Account',NULL,'Full','active','b85b776645f22268b9ae197c65fe5f32','Administrator','/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf')
----

* With the default one below


[source,lang:default,decode:true]
----
INSERT INTO "restcomm_accounts" VALUES('ACae6e420f425248d6a26948c17a9e2acf','2012-04-24 00:00:00.000000','2012-04-24 00:00:00.000000','administrator@company.com','Default Administrator Account',NULL,'Full','uninitialized','77f8c12cc7b8f8423e5c38b035249166','Administrator','/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf')

----

* Save the *sbc.script* file
* Go to the directory *$SBC_HOME/bin*
* Stop the running Restcomm-SBC instance by executing the script *./catalina.sh stop*
* Start Restcomm-SBC by executing the script *./catalina.sh start*

IMPORTANT: You must have configured the sbc.conf file in order to use the Stop and Start restcomm-sbc script.
