package org.restcomm.sbc.bo;

import org.joda.time.DateTime;

// Generated 24-jun-2016 11:18:37 by Hibernate Tools 3.5.0.Final



/**
 * Calls generated by hbm2java
 */

public class Calls implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8297663798076021150L;
	private int uid;
	private String fromUser;
	private String toUser;
	private String fromIp;
	private DateTime startTime;
	private Integer status;

	public Calls() {
	}

	public Calls(int uid) {
		this.uid = uid;
	}

	public Calls(int uid, String fromUser, String toUser, String fromIp, DateTime startTime, Integer status) {
		this.uid = uid;
		this.fromUser = fromUser;
		this.toUser = toUser;
		this.fromIp = fromIp;
		this.startTime = startTime;
		this.status = status;
	}


	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}


	public String getFromUser() {
		return this.fromUser;
	}

	public void setFromUser(String fromUser) {
		this.fromUser = fromUser;
	}

	
	public String getToUser() {
		return this.toUser;
	}

	public void setToUser(String toUser) {
		this.toUser = toUser;
	}

	
	public String getFromIp() {
		return this.fromIp;
	}

	public void setFromIp(String fromIp) {
		this.fromIp = fromIp;
	}

	
	public DateTime getStartTime() {
		return this.startTime;
	}

	public void setStartTime(DateTime startTime) {
		this.startTime = startTime;
	}

	
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
