== The Notification Sub-system Framework


As the _Chain subsystem_ is responsible to deal with message analysis in order to detect any SBC business rule violation, a _Notification subsystem_ is responsible to report some tracking information of events detected to other actors on the system.

There exists many kinds of notifications that an SBC would need to perform its whole task. the _Notification subsystem_ considers three main types:

* Accounting
* Alerting
* Tracking

.Notifiable.java
[source,java]
----
public interface Notifiable {
	
	/**
	 * Gets Threat timestamp
	 * @return timestamp
	 */
	long getTimestamp();
	
	/**
	 * Sends notification
	 */
	void send();
	
	/**
	 * Notification was sent already
	 * @return boolean
	 */
	boolean isAlreadySent();

}
----

=== Accounting

Usually related to persistent data for further analisys.
For instance: CDRs, Activity LOGs, Media Recording, etc.

=== Alerting

Usually related to instant notification of potential _Threat_ arising. For instance: SNMP alert, SMTP Alert and other alerting implementation subclasses.

.Alertable.java
[source,java]
----
public interface Alertable extends Notifiable {
	
	/**
	 * Gets Threat
	 * @return Threat
	 */
	Threat getThreat();
	
}
----

=== Tracking

TODO