= Restcomm SBC API – Ban List

[[BanLists]]
== BanLists

Ban lists perform allow/deny access control (ACL) at IP address level. Two implementations of BanLists are available: WhiteList and BlackList.
WhiteList allows certain IP Addresses to reach DMZ interfaces while BlackList blocks them at all. White/Black list consistence is controlled by the system while Black lists have precedence analysis over White ones.

=== BanList Resource URI

*/2012-04-24/[WhiteLists|BlackLists]/\{IpAddress}*

=== Resource Properties

[cols=",",options="header",]
|=========================================================================================================================
|Property |Description
|IpAddress |A string that uniquely identifies the host/net address.
|DateCreated |The date that this entry was created.
|DateExpires |The date that this entry will expire.
|Reason |A description of the cause this entry is included in the list, available options are: Threat, Admin.
|Action |The action to be taken for further processing.
|AccountSid |The account ID who created the entry.
|=========================================================================================================================

=== Supported Operations

*HTTP GET.* Returns the representation of an BanList resource, including the properties above.

* BanList Resource URI. */2012-04-24/[WhiteList|BlackList]/\{IpAddress}*

**HTTP POST/PUT**. Creates a new BanList entry resource and returns the representation, including the properties above. Below you will find a list of optional parameters.

=== Request Parameters

[cols=",",options="header",]
|==============================================================================================
|Parameter |Description
|IpAddress |A description of the address, up to 64 characters long.
|==============================================================================================

**Get information about a BanList.**

....
curl -X GET  http://ACae6e420f425248d6a26948c17a9e2acf:77f8c12cc7b8f8423e5c38b035249166@127.0.0.1:8080/restcomm-sbc/2012-04-24/WhiteList
....


The above commands will print an output similar to the one below:

----

 <RestcommResponse>
  <BanLists page="0" numpages="0" pagesize="50" total="0" start="0" end="4" uri="/restcomm-sbc/2012-04-24/WhiteList" firstpageuri="/restcomm-sbc/2012-04-24/WhiteList?Page=0&amp;PageSize=50" previouspageuri="null" nextpageuri="null" lastpageuri="/restcomm-sbc/2012-04-24/WhiteList?Page=0&amp;PageSize=50">
     <WhiteList>
       <DateCreated>Mon, 25 Jul 2016 08:14:57 -0300</DateCreated>
       <DateExpires>Mon, 25 Jul 2016 08:14:57 -0300</DateExpires>
       <AccountSid>ACae6e420f425248d6a26948c17a9e2acf</AccountSid>
       <IpAddress>192.168.0.32</IpAddress>
       <Action>Apply</Action>
       <Reason>Admin</Reason>
     </WhiteList>
     <WhiteList>
       <DateCreated>Mon, 25 Jul 2016 08:15:58 -0300</DateCreated>
       <DateExpires>Mon, 25 Jul 2016 08:15:58 -0300</DateExpires>
       <AccountSid>ACae6e420f425248d6a26948c17a9e2acf</AccountSid>
       <IpAddress>192.168.0.33</IpAddress>
       <Action>Apply</Action>
       <Reason>Admin</Reason>
     </WhiteList>
     <WhiteList>
       <DateCreated>Tue, 26 Jul 2016 13:57:17 -0300</DateCreated>
       <DateExpires>Tue, 26 Jul 2016 13:57:17 -0300</DateExpires>
       <AccountSid>ACae6e420f425248d6a26948c17a9e2acf</AccountSid>
       <IpAddress>192.168.2.33</IpAddress>
       <Action>Remove</Action>
       <Reason>Threat</Reason>
     </WhiteList>
     <WhiteList>
       <DateCreated>Tue, 26 Jul 2016 14:30:29 -0300</DateCreated>
       <DateExpires>Tue, 26 Jul 2016 14:30:29 -0300</DateExpires>
       <AccountSid>ACae6e420f425248d6a26948c17a9e2acf</AccountSid>
       <IpAddress>192.168.2.38</IpAddress>
       <Action>Apply</Action>
       <Reason>Admin</Reason>
     </WhiteList>
   </BanLists>
 </RestcommResponse>
----


[[entry-creation]]
== Entry creation


Here is an example of how to create a new ban entry.

....
curl -X POST http://administrator%40company.com:77f8c12cc7b8f8423e5c38b035249166@127.0.0.1:8080/restcomm-sbc/2012-04-24/WhiteList/ -d "IpAddress=201.215.232.188" 
....


=== Supported Operations

[[delete-entry]]
=== Delete Entries

.XML Entry Deletion
----
curl -X DELETE http://ACae6e420f425248d6a26948c17a9e2acf:PWD@192.168.1.3:8080/restcomm-sbc/2012-04-24/WhiteList/<IP-ADDRESS>
----

.JSON Entry Deletion
----
curl -X DELETE http://ACae6e420f425248d6a26948c17a9e2acf:PWD@192.168.1.3:8080/restcomm/2012-04-24/WhiteList.json/<IP-ADDRESS>.json
----


NOTE: the **IpAddress** deletion just tags the entry to be removed by the system monitoring thread.
