= Restcomm SBC API – Location

[[Locations]]
== Locations

Location cache stores authenticated and authorized registration request.


=== Location Resource URI

*/2012-04-24/Locations/\{User}*

=== Resource Properties

[cols=",",options="header",]
|=========================================================================================================================
|Property |Description
|User |A string that uniquely identifies this location entry.
|Host |IP Address/Domain of the user.
|Port |Port number.
|Transport| A string representing SIP transport (UDP/TCP/TLS/WS)
|DmzExpireTimestamp |The location's expiration time from DMZ perspective.
|MzExpireTimestamp |The location's expiration time from MZ perspective.
|UserAgent |A description of the registered endpoint.
|=========================================================================================================================

=== Supported Operations

*HTTP GET.* Returns the representation of an Location resource, including the properties above.

* Account Resource URI. */2012-04-24/Locations/\{User}*

**HTTP POST**. Returns the Location representation, including the properties above. Below you will find a list of optional parameters.

=== Request Parameters

[cols=",",options="header",]
|==============================================================================================
|Parameter |Description
|User |A string that uniquely identifies this location entry.
|==============================================================================================

**Get information about the location.**

....
curl -X GET  http://ACae6e420f425248d6a26948c17a9e2acf:77f8c12cc7b8f8423e5c38b035249166@127.0.0.1:8080/restcomm-sbc/2012-04-24/Locations
....



....
curl -X GET  http://administrator%40company.com:77f8c12cc7b8f8423e5c38b035249166@127.0.0.1:8080/restcomm-sbc/2012-04-24/Locations/00
....

The above commands will print an output similar to the one below:

----

<RestcommResponse>
    <Locations page="0" numpages="0" pagesize="50" total="0" start="0" end="1" uri="/restcomm-sbc/2012-04-24/Locations" firstpageuri="/restcomm-sbc/2012-04-24/Locations?Page=0&amp;PageSize=50" previouspageuri="null" nextpageuri="null" lastpageuri="/restcomm-sbc/2012-04-24/Locations?Page=0&amp;PageSize=50">
     <Location>
       <Host>192.168.0.2</Host>
       <User>00</User>
       <Transport>UDP</Transport>
       <DmzExpireTimestamp>1469214880694</DmzExpireTimestamp>
       <MzExpireTimestamp>1469214880694</MzExpireTimestamp>
       <UserAgent>friendly-scanner</UserAgent>
       <Port>5060</Port>
     </Location>
   </Locations>
 </RestcommResponse>

----

[[Locations_List]]
== Location List Resource

* Location List Resource URI. */2012-04-24/Locations*

=== Supported Operations

**HTTP GET**. Returns the list representation of all the *Locations* resources. 


=== Request Parameters

[cols=",",options="header",]
|==============================================================================================================================================================================================================================
|Parameter |Description
|User(Required) |The user account.
|==============================================================================================================================================================================================================================


=== Get a list of all current locations

----
curl -X GET http://[primarySid]:[primaryAuthToken]@127.0.0.1:8080/restcomm-sbc/2012-04-24/Locations/
----


=== Supported Operations


----
<RestcommResponse>
    <Locations page="0" numpages="0" pagesize="50" total="0" start="0" end="4" uri="/restcomm-sbc/2012-04-24/Locations" firstpageuri="/restcomm-sbc/2012-04-24/Locations?Page=0&amp;PageSize=50" previouspageuri="null" nextpageuri="null" lastpageuri="/restcomm-sbc/2012-04-24/Locations?Page=0&amp;PageSize=50">
     <Location>
       <Host>192.168.0.2</Host>
       <User>00</User>
       <Transport>UDP</Transport>
       <DmzExpireTimestamp>1469214880694</DmzExpireTimestamp>
       <MzExpireTimestamp>1469214880694</MzExpireTimestamp>
       <UserAgent>friendly-scanner</UserAgent>
       <Port>5060</Port>
     </Location>
     <Location>
       <Host>192.168.0.2</Host>
       <User>01</User>
       <Transport>UDP</Transport>
       <DmzExpireTimestamp>1469214880694</DmzExpireTimestamp>
       <MzExpireTimestamp>1469214880694</MzExpireTimestamp>
       <UserAgent>friendly-scanner</UserAgent>
       <Port>5060</Port>
     </Location>
   </Locations>
 </RestcommResponse>
----

[[delete-locations]]
=== Delete Location

.XML Location Deletion
----
curl -X DELETE http://ACae6e420f425248d6a26948c17a9e2acf:PWD@192.168.1.3:8080/restcomm-sbc/2012-04-24/Locations/<User>
----

.JSON Location Deletion
----
curl -X DELETE http://ACae6e420f425248d6a26948c17a9e2acf:PWD@192.168.1.3:8080/restcomm-sbc/2012-04-24/Locations.json/<User>.json
----
