= Restcomm API – Routes

[[Routes]]
== Routes

Routes are paths from a DMZ connector service to an MZ connector service.
A Route links a connector giving service on a Network point to another connector giving service on Network point of the counterpath zone.


.Routes example, multiple Connector forwarding
[ditaa,routes,png]
--

                DMZ  +---------------------+  MZ
                     |                     |
 ---Connector A -----> --------------------+---Connector D-->
                     |                     |
 ---Connector B -----> --------------------+---Connector C--> 
                     |                     |
                     +---------------------+
                   
--


NOTE: Routes have nothing to do with IP Addresses. They are assigned from the NetworkPoint/Connector they belong to at run-time.

WARNING: Routes are allways created with a DMZ origin and an MZ target.

A Route is a DMZ entity. Similar to firewall rules that allow to forward traffic from public interfaces to private ones.

=== Routes Resource URI

*/2012-04-24/Routes/\{Sid}*

=== Resource Properties

[cols=",",options="header",]
|=========================================================================================================================
|Property |Description
|Sid |A string that uniquely identifies this route entry.
|SourceConnectorSid |A string that uniquely identifies the DMZ source Connector that offers service.
|TargetConnectorSid |A string that uniquely identifies the MZ Connector that this route is forwarded to.
|AccountSid | Unique identifier representing the account that tagged the Network point.
|=========================================================================================================================

=== Supported Operations

*HTTP GET.* Returns the representation of an Route resource, including the properties above.

* Route Resource URI. */2012-04-24/Routes/\{Sid}*

**HTTP POST**. Returns the Route representation, including the properties above. Below you will find a list of optional parameters.

=== Request Parameters

[cols=",",options="header",]
|==============================================================================================
|Parameter |Description
|Sid |A string that uniquely identifies this Route entry.
|==============================================================================================

**Get information about the Route.**

....
curl -X GET  http://ACae6e420f425248d6a26948c17a9e2acf:77f8c12cc7b8f8423e5c38b035249166@127.0.0.1:8080/restcomm-sbc/2012-04-24/Routes
....
The above commands will print an output similar to the one below:
....
<RestcommResponse>
  <Routes>
    <Route>
      <Sid>RTae6e420f425248d6a26948c17a9e2aaa</Sid>
      <SourceConnectorSid>CNae6e420f425248d6a26948c17a9e2aaa</SourceConnectorSid>
      <TargetConnectorSid>CNae6e420f425248d6a26948c17a9e2bbb</TargetConnectorSid>
      <AccountSid>ACae6e420f425248d6a26948c17a9e2acf</AccountSid>
    </Route>
    <Route>
      <Sid>RTae6e420f425248d6a26948c17a9e2bbb</Sid>
      <SourceConnectorSid>CNae6e420f425248d6a26948c17a9e2ccc</SourceConnectorSid>
      <TargetConnectorSid>CNae6e420f425248d6a26948c17a9e2bbb</TargetConnectorSid>
      <AccountSid>ACae6e420f425248d6a26948c17a9e2acf</AccountSid>
    </Route>
  </Routes>
</RestcommResponse>
....
....
curl -X GET  http://administrator%40company.com:77f8c12cc7b8f8423e5c38b035249166@127.0.0.1:8080/restcomm-sbc/2012-04-24/Routes/RTae6e420f425248d6a26948c17a9e2aaa
....

The above commands will print an output similar to the one below:

----
<RestcommResponse>
    <Route>
      <Sid>RTae6e420f425248d6a26948c17a9e2aaa</Sid>
      <SourceConnectorSid>CNae6e420f425248d6a26948c17a9e2aaa</SourceConnectorSid>
      <TargetConnectorSid>CNae6e420f425248d6a26948c17a9e2bbb</TargetConnectorSid>
      <AccountSid>ACae6e420f425248d6a26948c17a9e2acf</AccountSid>
    </Route>
</RestcommResponse>

----

[[Routes_List]]
== Routes List Resource

* Routes List Resource URI. */2012-04-24/Routes*

=== Supported Operations

**HTTP GET**. Returns the list representation of all the *Routes* resources.

**HTTP POST**. Adds a *Route* resource.

**HTTP DELETE**. Deletes a *Route* resource.

=== Request Parameters

[cols=",",options="header",]
|==============================================================================================================================================================================================================================
|Parameter |Description
|Sid(Required) |The unique identifier.
|==============================================================================================================================================================================================================================


=== Get a list of all current routes

----
curl -X GET http://[primarySid]:[primaryAuthToken]@127.0.0.1:8080/restcomm-sbc/2012-04-24/Routes/
----


=== Supported Operations


----

 <RestcommResponse>
   <Routes>
     <Route>
       <Sid>RTedc0bce80638e78ee20d68dc748d905f</Sid>
       <SourceConnectorSid>CNedc0bce80638e78ee20d68dc748d905f</SourceConnectorSid>
       <TargetConnectorSid>CNb65727e434f182b7215ea95105b66ed9</TargetConnectorSid>
       <AccountSid>ACae6e420f425248d6a26948c17a9e2acf</AccountSid>
     </Route>
   </Routes>
 </RestcommResponse>

----
[[add-routes]]
=== Add a Route

.XML Route adding
----
curl -X POST http://ACae6e420f425248d6a26948c17a9e2acf:PWD@192.168.1.3:8080/restcomm-sbc/2012-04-24/Routes/ -d "SourceConnectorSid=CNedc0bce80638e78ee20d68dc748d905f" -d "TargetConnectorSid=CNb65727e434f182b7215ea95105b66ed9" 
----


[[delete-routes]]
=== Delete Route

.XML Route delete
----
curl -X DELETE http://ACae6e420f425248d6a26948c17a9e2acf:PWD@192.168.1.3:8080/restcomm-sbc/2012-04-24/Routes/<Sid>
----
