= Restcomm API – Routes

[[Routes]]
== Routes

Connectors represents SIP services. Connectors are bound/unbound all over tagged Network Points.

.Routes example, multiple Connector forwarding
[ditaa,routes,png]
--

                DMZ  +---------------------+  MZ
                     |                     |
 ---Connector A -----> --------------------+---Connector D-->
                     |                     |
 ---Connector B -----> --------------------+---Connector C--> 
                     |                     |
                     +---------------------+
                   
--


NOTE: Routes have nothing to do with IP Addresses. They are assigned from the NetworkPoint/Connector they belong to at run-time.

A Route is a DMZ entity. Similar to firewall rules that allow to forward traffic from public interfaces to private ones.

=== Routes Resource URI

*/2012-04-24/Routes/\{Sid}*

=== Resource Properties

[cols=",",options="header",]
|=========================================================================================================================
|Property |Description
|Sid |A string that uniquely identifies this route entry.
|SourceConnectorSid |A string that uniquely identifies the DMZ source Connector that offers service.
|TargetConnectorSid |A string that uniquely identifies the MZ Connector that this route is forwarded to.
|AccountSid | Unique identifier representing the account that tagged the Network point.
|=========================================================================================================================

=== Supported Operations

*HTTP GET.* Returns the representation of an Route resource, including the properties above.

* Route Resource URI. */2012-04-24/Routes/\{Sid}*

**HTTP POST**. Returns the Route representation, including the properties above. Below you will find a list of optional parameters.

=== Request Parameters

[cols=",",options="header",]
|==============================================================================================
|Parameter |Description
|Sid |A string that uniquely identifies this Route entry.
|==============================================================================================

**Get information about the Route.**

....
curl -X GET  http://ACae6e420f425248d6a26948c17a9e2acf:77f8c12cc7b8f8423e5c38b035249166@127.0.0.1:8080/restcomm-sbc/2012-04-24/Routes
....



....
curl -X GET  http://administrator%40company.com:77f8c12cc7b8f8423e5c38b035249166@127.0.0.1:8080/restcomm-sbc/2012-04-24/Routes/{Sid}
....

The above commands will print an output similar to the one below:

----
<RestcommResponse>
    <Connector>
       <IpAddress>192.168.88.2</IpAddress>
       <Sid>CNedc0bce80638e78ee20d68dc748d905f</Sid>
       <Port>5060</Port>
       <NetworkPointId>eth1-1</NetworkPointId>
       <Transport>UDP</Transport>
       <State>UP</State>
       <AccountSid>ACae6e420f425248d6a26948c17a9e2acf</AccountSid>
     </Connector>
 </RestcommResponse>

----

[[Connectors_List]]
== Connectors List Resource

* Connectors List Resource URI. */2012-04-24/Connectors*

=== Supported Operations

**HTTP GET**. Returns the list representation of all the *Connectors* resources.

**HTTP POST**. Adds a *Connector* resource.

**HTTP POST**. Plug an unplugged *Connector* resource.

**HTTP POST**. UnPlug a plugged *Connector* resource.

**HTTP DELETE**. Deletes a *Connector* resource.

=== Request Parameters

[cols=",",options="header",]
|==============================================================================================================================================================================================================================
|Parameter |Description
|Sid(Required) |The unique identifier.
|==============================================================================================================================================================================================================================


=== Get a list of all current connectors

----
curl -X GET http://[primarySid]:[primaryAuthToken]@127.0.0.1:8080/restcomm-sbc/2012-04-24/Connectors/
----


=== Supported Operations


----

 <RestcommResponse>
   <Routes>
     <Route>
       <Sid>RTedc0bce80638e78ee20d68dc748d905f</Sid>
       <SourceConnectorSid>CNedc0bce80638e78ee20d68dc748d905f</SourceConnectorSid>
       <TargetConnectorSid>CNb65727e434f182b7215ea95105b66ed9</TargetConnectorSid>
       <AccountSid>ACae6e420f425248d6a26948c17a9e2acf</AccountSid>
     </Route>
   </Routes>
 </RestcommResponse>

----
[[add-connectors]]
=== Add a Connector

.XML Connector adding
----
curl -X POST http://ACae6e420f425248d6a26948c17a9e2acf:PWD@192.168.1.3:8080/restcomm-sbc/2012-04-24/Connectors/ -d "NetworkPointId=eth0-0" -d "Transport=UDP" -d "Port=5060"
----


NOTE: Connectors are first created in DOWN State. Yo have to plug it to put it on service (UP State).

[[plug-connectors]]
=== Plug a Connector

.XML Connector plugging
----
curl -X POST http://ACae6e420f425248d6a26948c17a9e2acf:PWD@192.168.1.3:8080/restcomm-sbc/2012-04-24/Connectors/ -d "Sid=CNedc0bce80638e78ee20d68dc748d905f" -d "State=UP"
----

[[unplug-connectors]]
=== Unplug a Connector

.XML Connector unplugging
----
curl -X POST http://ACae6e420f425248d6a26948c17a9e2acf:PWD@192.168.1.3:8080/restcomm-sbc/2012-04-24/Connectors/ -d "Sid=CNedc0bce80638e78ee20d68dc748d905f" -d "State=DOWN"
----


[[delete-connectors]]
=== Delete Connector

.XML Connector delete
----
curl -X DELETE http://ACae6e420f425248d6a26948c17a9e2acf:PWD@192.168.1.3:8080/restcomm-sbc/2012-04-24/Connectors/<Sid>
----
